### PR TITLE
GSEA to AGSEA Appyter Update

### PR DESCRIPTION
**Pull request by cindyxio**
- Created Highlighting Co-expressed Genes Section
- Added CD and limma as ranking method
- Added figure captions
- Various minor changes

### CODE REVIEW

**Comment by cindyxio** [comment]
The test is taking a while because there's currently degraded performance for Github Actions.

**Comment by u8sand** [comment]
@cindyxio the test will fail because the folder needs to be renamed according to the `name`

**Comment by cindyxio** [comment]
@u8sand thanks for letting me know! Is there a way to rename the folder, or would I have to delete it and create a new one?

**Comment by u8sand** [comment]
`git mv appyters/GSEA_Appyter  appyters/AGSEA_Appyter`

Make sure it's in its own commit, otherwise git may get confused and consider it a deletion & addition

**Comment by u8sand** [comment]
It also seems like your feature_image got deleted?

**Comment by cindyxio** [comment]
I'm not sure why the version update in appyter.json is not working, and I tried to change it again. Is it okay if I close this pull request and re-fork from the appyter catalog? I am thinking of changing the `name` back in appyter.json to GSEA_Appyter to match the folder, instead of creating a new folder to match the `name`, because maybe it's getting confused since I deleted the GSEA_Appyter folder.

**Pull request closed without merging**
