### PR TITLE
simple fix for no normalization bug

### PR DESCRIPTION
**Pull request by thereidfleish**
When selecting "None" for the normalization method, the Appyter would raise an error because it could not find the "adata_norm" variable, which is only assigned during normalization and is referenced 30+ times after in the Appyter.

This is a simple fix that assigns the variable to the un-normalized data if the user selects "None."  Ideally, this would be named something different (because the data isn't actually normalized), but this would require refactoring many of the subsequent variable names.

### CODE REVIEW

**Comment by u8sand** [comment]
Looks reasonable, I'm running validation locally

**Comment by thereidfleish** [comment]
Whoops, my Tumor Gene Target Screener commit got put into this PR...sorry, I'm not the most experienced with Github.

Anyway, here are the changes to the Tumor Gene Target Screener Appyter:
1. Adds the ability to input scRNA-seq data into the Appyter
2. Add logo
3. Update wording to make the Appyter's function more broad (e.g., not just tumors)

**Comment by u8sand** [comment]
Please move it to another branch and submit a new PR. then reset this one

**Comment by thereidfleish** [comment]
> Please move it to another branch and submit a new PR. then reset this one

ok, i think i did this right...

**Comment by u8sand** [comment]
This still has an error unfortunately, i'm not entirely sure what is going on.

```
rnaseq_data_filename1 = ""
mtx_data_filename1 = ""
gene_data_filename1 = ""
barcode_data_filename1 = ""
mtx_data_filename1 = 'example_matrix_GDC_C3N-00662.mtx'
gene_data_filename1 = 'example_features_GDC_C3N-00662.tsv'
barcode_data_filename1 = 'example_barcodes_GDC_C3N-00662.tsv'
meta_data_filename1 = None
meta_class_column_name1 = ''
dataset_name1 = "Dataset1"

...

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [11], in <cell line: 4>()
      1 adata_list = list()
      2 adata_adt_list = list()
----> 4 adata1, table_counter, meta_class_column_name = load_data(dataset_name1, rnaseq_data_filename1, mtx_data_filename1, gene_data_filename1, barcode_data_filename1, meta_data_filename1, meta_class_column_name1, table_counter)
      5 adata2, table_counter, _ = load_data(dataset_name2, rnaseq_data_filename2, mtx_data_filename2, gene_data_filename2, barcode_data_filename2, meta_data_filename2, meta_class_column_name2, table_counter)
      6 adata3, table_counter, _ = load_data(dataset_name3, rnaseq_data_filename3, mtx_data_filename3, gene_data_filename3, barcode_data_filename3, meta_data_filename3, meta_class_column_name3, table_counter)

File ~/utils.py:151, in load_data(dataset_name, rnaseq_data_filename, mtx_data_filename, gene_data_filename, barcode_data_filename, meta_data_filename, meta_class_column_name, table_counter)
    148     adata = load_seurat_files(mtx_data_filename, gene_data_filename, barcode_data_filename)
    149 if adata is not None:
    150     # load meta data
--> 151     adata, meta_class_column_name = load_metadata(adata, meta_data_filename, meta_class_column_name)    
    153     # add batch info
    154     if meta_class_column_name == "":

File ~/utils.py:106, in load_metadata(adata, meta_data_filename, meta_class_column_name)
    104 def load_metadata(adata, meta_data_filename, meta_class_column_name):
    105     if meta_data_filename != "":
--> 106         if meta_data_filename.endswith(".csv"):
    107             meta_df = pd.read_csv(meta_data_filename, index_col=0)
    108         else:

AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by thereidfleish** [comment]
This is weird...I didn't change anything beyond what is in the commits, and it doesn't look like my changes would affect this.  Perhaps this is a bug that existed prior to my changes that wasn't caught...

I'll make that change you suggest and re-commit

**Comment by u8sand** [comment]
@thereidfleish don't worry about it, i'm working on fixing it, thanks for the initial push

**Pull request closed without merging**
