### PR TITLE
GSEA Appyter v1 Upload

### PR DESCRIPTION
**Pull request by cindyxio**
This is the first version of the Appyter that creates a table for GSEA results, an interactive Enrichment Plot, and a Hit Indices plot.

### CODE REVIEW

**Comment by u8sand** [comment]
Please make `name` the same as the directory name, this is case sensitive.

**Comment by u8sand** [comment]
Why did you close this?

**Comment by cindyxio** [comment]
I saw that some of the past pull requests closed it and opened a new one after fixing an issue. Sorry if I wasn't supposed to; I wasn't sure if I was supposed to or not?

**Comment by u8sand** [comment]
If you want this to be in the catalog you'll need to leave it open so I can merge it. How does this PR relate to your newer PR?

**Comment by cindyxio** [comment]
They're the same; I just re-uploaded the newly edited files which is why there are less commits. Is it possible to merge the newer one?

**Pull request closed without merging**
