### PR TITLE
Add Figure Titles, Figure Legends, FET Dropdown

### PR DESCRIPTION
**Pull request by homjason**

### CODE REVIEW

**Comment by homjason** [comment]
The check says that appyter nbconstruct CompareSets.ipynb check failed. Could this be because I don't have a default for every field? I have defaults for 3 of the text inputs which should allow the appyter to work. Or is there something else I'm missing?

**Comment by u8sand** [comment]
You should be able to test it locally and maybe see what the issue is, if it is something with appyters, I can fix it but I'm not sure..

```
CompareSets: `appyter nbconstruct CompareSets.ipynb` < {'section0': None, 'section1': None, 'section2': None, 'section3': None, 'section4': None, 'gs1': '', 'gs2': '', 'gs3': '', 'gs4': '', 'gs5': '', 'gs6': '', 'gs1Text': 'TRPV1\nOPRM1\nTRPA1\nCOMT\nSCN9A\nTNF\nIL6\nIL1B\nCRP\nBDNF\nNGF\nSLC6A4\nMEFV\nTRPM8\nTRPV4\nCALCA\nNTRK1\nTLR4\nASIC3\nSCN10A\nMMP9\nCNR1\nIL10\nCCL2\nTNNT2\nNPPB\nPTGS2\nCYP2D6\nP2RX3\nTACR1', 'gs2Text': 'TNF\nTRPV1\nCRP\nFOS\nPTGS2\nNGF\nTRPA1\nBDNF\nCD34\nPOMC\nIVD\nIL10\nACE\nCASP3\nCCL2\nTLR4\nGFAP\nTRPM8\nIL6\nCD68\nKIT\nOPRM1\nSCN9A\nCYP2D6\nCOMT\nCEACAM5\nGDNF\nNPY\nPTH\nTRPV4', 'gs3Text': 'OPRD1\nTRPV1\nTRPA1\nSCN9A\nOPRM1\nTRPM8\nTACR1\nOPRK1\nTAC1\nSCN3B\nKCNS1\nTRPV3\nTRPV4\nCACNA1B\nCACNA2D2\nSCN11A\nNTRK1\nPENK\nSCN1B\nOPRL1\nPDYN\nTRPV2\nHTR3C\nHTR3A\nCOMT\nP2RX3\nTRPM5\nDRD2\nNGFR\nFAAH\nASIC3\nPNOC\nHTR3B\nTRPM4\nCACNA2D3\nBDKRB1\nASIC4\nHTR2A\nKCNC2\nCHRM4\nTRPM3\nHTR3E\nCACNG2\nCHRNA7\nSCN10A', 'gs4Text': '', 'gs5Text': '', 'gs6Text': '', 'venndiagram': 'true', 'scheme': 'viridis', 'venn_file_format': ['png'], 'venn_file_name': 'venn', 'upset': 'true', 'orient': 'Horizontal', 'color': 'black', 'counts': 'true', 'percent': 'false', 'figure_file_format': ['png'], 'output_file_name': 'UpSet_plot', 'background': 20000, 'significance': '0.05'}
CompareSets: ERROR `appyter nbconstruct CompareSets.ipynb` command failed
```

nbconstruct is used in production as well, this would mean that if you just click submit without changing anything then the appyter cannot even be constructed. I can potentially look more into it tomorrow..

**Comment by homjason** [comment]
I tested the notebook again locally and tried clicking submit without changing anything and it said it was constructed successfully. I re-added the notebook to the repo to see if it would fix anything, but I'm still failing the same test. If you can look at it when you get a chance, that would be great. Thanks!

**Comment by u8sand** [comment]
```
% appyter nbconstruct CompareSets.ipynb < input.json                                                                                                   
Traceback (most recent call last):
  File "/home/u8sand/.local/bin/appyter", line 8, in <module>
    sys.exit(main())
  File "/home/u8sand/.local/lib/python3.8/site-packages/appyter/__main__.py", line 11, in main
    cli()
  File "/home/u8sand/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/u8sand/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/u8sand/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/u8sand/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/u8sand/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/u8sand/.local/lib/python3.8/site-packages/appyter/render/nbconstruct.py", line 79, in nbconstruct
    nb = render_nb_from_nbtemplate(env, nbtemplate)
  File "/home/u8sand/.local/lib/python3.8/site-packages/appyter/render/nbconstruct.py", line 58, in render_nb_from_nbtemplate
    nb.cells = list(filter(None, [
  File "/home/u8sand/.local/lib/python3.8/site-packages/appyter/render/nbconstruct.py", line 59, in <listcomp>
    render_cell(
  File "/home/u8sand/.local/lib/python3.8/site-packages/appyter/render/nbconstruct.py", line 30, in render_cell
    rendered = template.render()
  File "/home/u8sand/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/u8sand/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/u8sand/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 130, in top-level template code
  File "/home/u8sand/.local/lib/python3.8/site-packages/appyter/fields.py", line 145, in __str__
    return self.safe_value
  File "/home/u8sand/.local/lib/python3.8/site-packages/appyter/profiles/default/fields/ChoiceField.py", line 23, in safe_value
    return self.value
  File "/home/u8sand/.local/lib/python3.8/site-packages/appyter/fields.py", line 125, in value
    assert self.constraint(), '%s[%s] (%s) does not satisfy constraints' % (
AssertionError: ChoiceField[color] (black) does not satisfy constraints
```

**Comment by homjason** [comment]
Thank you!

**Pull request merged**
