### PR TITLE
Fix bokeh output

### PR DESCRIPTION
**Pull request by skylar73**
Moved Bokeh output from output_file to output_notebook so even if it doesn't run in the appyter, it will run in the downloaded notebook.

### CODE REVIEW

**Comment by u8sand** [comment]
What isn't running in the appyter?

**Comment by skylar73** [comment]
When running the appyter locally I was having problems with the bokeh output showing up. Only "Loading BokehJS..." would show up. But, it runs and outputs correctly when the notebook is downloaded

**Comment by u8sand** [comment]
It would be good to address that issue instead. Bokeh plots should certainly work.. can you send me an example link to an appyter that doesn't work on the public site?

**Comment by u8sand** [comment]
I fixed this so your change should now work in production and locally if you update your appyter version

**Pull request merged**
