### PR TITLE
Steap

### PR DESCRIPTION
**Pull request by erwinerdem**

### CODE REVIEW

**Comment by u8sand** [comment]
Hey @erwinerdem -- awesome to see this contribution. We'll be happy to work with you on getting this merged.

I wonder if it might make sense to turn your [origin repository](https://github.com/erwinerdem/STEAP) into a python package for which the notebook could then import the scripts. Then you could pip install it on the appyter and import it, instead of duplicating the scripts here, let us know if this is something you'd be interested in.

**Comment by erwinerdem** [comment]
Hey @u8sand thanks for the comments! I've edited it just now.
Regarding making a python package: I was initially thinking this as well, but I made some changes to the STEAP scripts to accommodate the appyter so it wouldn't be that useful probably.

**Comment by u8sand** [comment]
@erwinerdem So this seems close now -- the docker image built properly and now it's just testing your defaults to ensure the notebook runs within the docker container.

On your FileFields, while you provided an example which is great, you should also provide a default for the purpose of testing:

So
```python
{% set ldsc_file = FileField(
    name='ldsc_file',
    label='The S-LDSC priotitization.csv file',
    examples={'ldsc.csv': 'https://github.com/erwinerdem/appyter_steap/raw/master/ldsc.csv'},
    section='Data_Section',
) %}
```

would become
```python
{% set ldsc_file = FileField(
    name='ldsc_file',
    label='The S-LDSC priotitization.csv file',
    examples={'ldsc.csv': 'https://github.com/erwinerdem/appyter_steap/raw/master/ldsc.csv'},
    default='ldsc.csv',
    section='Data_Section',
) %}
```

**Comment by u8sand** [comment]
FYI, here is the error parsed:

```
TypeError                                 Traceback (most recent call last)", "<ipython-input-1-98fc1060fd1e> in <module>
      1 import pandas as pd
      2 import constants # file which consists of constant for the analysis
----> 3 from scripts import convert_output_to_dataframe
      4 from scripts import gene_set_enrichment_analysis
      5 from scripts import calculate_beta_correlation
", "~/scripts/convert_output_to_dataframe.py in <module>
     14 
     15 
---> 16 def find_csv_file(directory: str) -> dict[str, dict[str, str]]:
     17     """
     18     Finds the priorirization.csv file in the input directory and uses the
TypeError: 'type' object is not subscriptable
```

**Comment by erwinerdem** [comment]
Ah yes thanks! That makes sense. I'll change it asap.

**Comment by u8sand** [comment]
So it's online, there is an issue but it's an issue another appyter had as well so I'm going to fix this upstream hopefully tomorrow.

https://appyters.maayanlab.cloud/STEAP_post_processing_analysis/

**Pull request merged**
